version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "react-scripts"
        versions: ["3.0.1"]
